-- MySQL Script generated by MySQL Workbench
-- Sat Dec  5 16:42:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lesson01
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lesson01
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lesson01` DEFAULT CHARACTER SET utf8 ;
USE `lesson01` ;

-- -----------------------------------------------------
-- Table `lesson01`.`city_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lesson01`.`city_type` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `short_name` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'тип населенного пункта';


-- -----------------------------------------------------
-- Table `lesson01`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lesson01`.`country` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `full_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `code2` CHAR(2) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `code3` CHAR(3) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lesson01`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lesson01`.`region` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `country_id` SMALLINT UNSIGNED NOT NULL,
  `code` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `country_id_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `country_id`
    FOREIGN KEY (`country_id`)
    REFERENCES `lesson01`.`country` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lesson01`.`district`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lesson01`.`district` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `region_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `region_id_idx` (`region_id` ASC) VISIBLE,
  INDEX `district_region_id_idx` (`region_id` ASC) VISIBLE,
  CONSTRAINT `region_district_id`
    FOREIGN KEY (`region_id`)
    REFERENCES `lesson01`.`region` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lesson01`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lesson01`.`city` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `region_id` INT UNSIGNED NOT NULL,
  `district_id` INT UNSIGNED NULL DEFAULT NULL,
  `city_type_id` SMALLINT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `city_type_id_idx` (`city_type_id` ASC) VISIBLE,
  INDEX `district_id_idx` (`district_id` ASC) VISIBLE,
  INDEX `region_id_idx` (`region_id` ASC) VISIBLE,
  CONSTRAINT `city_type_id`
    FOREIGN KEY (`city_type_id`)
    REFERENCES `lesson01`.`city_type` (`id`),
  CONSTRAINT `district_id`
    FOREIGN KEY (`district_id`)
    REFERENCES `lesson01`.`district` (`id`),
  CONSTRAINT `region_id`
    FOREIGN KEY (`region_id`)
    REFERENCES `lesson01`.`region` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
